### ISSUE TITLE
Missionen

### ISSUE THREAD

**Issue by Zumiii** [Zumiii/Brainstorm#1]
Hier Ideen anbringen

**Comment by Zumiii** [comment]
-IED Werkstatt (Gesprächsaufkärung -> Compound stürmen -> Terroristen festsetzen/ töten, beweise sammeln) -> weniger IEDs

**Comment by Zumiii** [comment]
Anschlag verhindern

**Comment by Zumiii** [comment]
kampfmittelräumung in unklarer lage
IED geht hoch, Hinterhalt, Abwehren

**Comment by Zumiii** [comment]
Warlord, der die Nahrungsmittel geklaut hat etc.

**Comment by Zumiii** [comment]
Schützen einer Lieferung

**Comment by Sim0nRiley** [comment]
Missionstask:

Klären Sie das Gebiet um (evtl. Koordinate oder Ortschaft) auf!
Nehmen Sie Kontakt mit den heimischen Zivilisten auf und fassen Sie die allgemeine Lage zusammen!


Ausführung: 

Patr. zu Fuss oder aufgessen auf Fahrzeug
Fahrt zu Punkt XXX
Zivilisten ansprechen
Deeskalierend wirken (Ausrüstungsabhängig, DRINGEND DARAUF ACHTEN!!!)

**Comment by Zumiii** [comment]
Rückführungen

**Comment by Zumiii** [comment]
Versteck finden, Beweise sichern

**Comment by Zumiii** [comment]
Eigene Nachschubgüter holen

**Comment by Zumiii** [comment]
Dorf frei kämpfen

**Comment by Zumiii** [comment]
Industrie etc. freikämpfen

**Comment by Sim0nRiley** [comment]
Missionstask:

Eine Zivile Verbindungsperson meldet in der Ortschaft (XXX???) den Missbrauch von Sprengkörpern
zum Erstellen von Sprengfallen!
Nehmen Sie Kontakt mit der Person auf zur Klärung der Standorte!

Ausführung:

Interaktion mit Zivilist der sich in Ortschaft (XXX) befindet um die Standorte der Sprengfallen zu erfahren. 
Entschärfung der Sprengfalle durch EOD
Ermitteln der Art der Sprengfalle
Bergung und Rückführung des Sprengkörpers

**Comment by Sim0nRiley** [comment]
Missionstask:

Ein Ziviler Tanklaster wurde im Ortskern von (xxx) gesprengt, die Zivilen Opferzahlen sind hoch, jedoch im Detail unbestätigt!
Begeben Sie sich an den Ort zur Untersuchung der Explosion! Achten Sie auf feindliche Hinterhalte da die Lage vor Ort ungeklärt ist!

Ausführung:

Explosionsort anfahren, evtl verwundete Zivilisten versorgen, nach verbleibendem Sprengstoff suchen.
Möglichen Hinterhalt von Feindkräften zerschlagen
Zivilbevölkerung schützen

**Comment by Zumiii** [comment]
Mörsermunition finden und kontrolliert sprengen

**Comment by Zumiii** [comment]
Strassensperre öffnen
